[tool.poetry]
name = "hydrogen-concentration"
version = "0.1.0"
description = ""
authors = ["faraz-m-awan <faraz.awan0406@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
